### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by l-jonas**
This closes https://github.com/syncthing/syncthing-lite/issues/38

### CODE REVIEW

**Comment by Nutomic** [comment]
I would just run this immediately before a release, so we have the latest translations. Or do you want to make a release just for the translations?

You are also missing translations for new languages here.

**Comment by l-jonas** [comment]
@Nutomic I don't want to hardlink this with the release process because there could be problems caused by this like now where some strings are not escaped correctly. In this case, I would make a release just for the translations because there are many changes.

**Comment by Nutomic** [comment]
Okay fine. In this case we should replace or remove the prepare-release.bash and publish-release.bash scripts (although I never had problems with this with Syncthing Android).

You still need to add all the new translations that were added. `tx pull -a` should do that.

**Comment by Nutomic** [comment]
Are you trying to fix the escaping after pulling from Transifex? This should be done automatically. Apostrophes should be written like `\'` (single backslash).

https://stackoverflow.com/a/5657189

**Comment by l-jonas** [comment]
@Nutomic The escaping should happen in the strings.xml. If it happens already in Transifex, it becomes a double backslash and the apostrophe which is wrong again. But this is fixed already.

**Comment by Nutomic** [comment]
Okay I see, I made an announcement about that on Transifex.

**Comment by Nutomic** [comment]
Huh, the build log says that it was successful, but it's showing an error. No idea what's going on.

**Comment by l-jonas** [comment]
@Nutomic There are errors. The problem is that the placeholders in the strings are not equal in the different languages (sometimes missing).

**Comment by Nutomic** [comment]
Oh it was with the lint output, I only looked at the build command at the end.

**Comment by Nutomic** [comment]
Fixed them in Transifex.

**Comment by Nutomic** [comment]
Do you want to remove the release scripts then? And make a new release?

**Pull request merged**
