### PR TITLE
Use sqlite with Room as db abstraction

### PR DESCRIPTION
**Pull request by l-jonas**
This depends on https://github.com/syncthing/syncthing-java/pull/18

### CODE REVIEW

**Comment by l-jonas** [comment]
I would prefer to access the database directly instead of using the FolderBrowser from syncthing-java as this would improve the code quality of the client (but it would lock the App into using this implementation).

**Comment by Nutomic** [comment]
Why don't you take all this database code, and put it into the library? With this implementation, a different library user would have to copy everything, which makes using the library pretty complicated. Of course no one else is using the library (afaik), but it still seems like a bad idea.

**Comment by AudriusButkevicius** [comment]
Perhaps there should be a separate db layer package.

**Comment by l-jonas** [comment]
@Nutomic DB abstraction was outsourced into an android library. I would suggest to move syncthing-java into this repository (as library projects in android studio) to make development easier (no step in between using a local maven repo + cleanly synchronized app and library version + no more two merge requests if a library change is required for an app change)

**Comment by Nutomic** [comment]
I agree that it would make development easier. But if someone wants to use the Syncthing protocol from Java in another project in the future, we'd have to move it all out into a seperate project again. Not sure if that makes sense. 

@AudriusButkevicius What do you think about merging syncthing-lite and syncthing-java?

**Comment by l-jonas** [comment]
I don't think that we would have to move it out. If someone else wants to use it, we would have to publish it on jcenter or somewhere like that.

**Comment by l-jonas** [comment]
@Nutomic Yes, that's what I've thought of. After this, it would be a good idea to update the Readme of syncthing-java to indicate that further work happens in syncthing-lite and to mark syncthing-java as read only.

**Comment by AudriusButkevicius** [comment]
@Nutomic there is only one user, so do whatever you feel is necessery. Also, not much of -java is left given it's written in kotlin.

**Comment by Nutomic** [comment]
@l-jonas Build is failing with some errors about Bouncycastle. I think you just need to ignore those classes in proguard.

@AudriusButkevicius It means we don't have to build the library *and* the app every time there is a change in the library. Kotlin should be pretty easy to use from Java. Iirc Kotlin uses the same collection types as Java. Here is some more info if you're curious: https://kotlinlang.org/docs/reference/java-to-kotlin-interop.html

**Comment by AudriusButkevicius** [comment]
You could publish the library to maven and then just depend on latest.release, this way automating the process and doing --refresh-dependencies part of PR CI to make sure its still compatible. Or even trigger app rebuilds as the lib gets released.

Also, the app is currently delisted from the store. Given a fair amount of work went into this, should we re-list it and release it at some point?

**Comment by AudriusButkevicius** [comment]
Or you could have a subrepo (git module) which acts as a gradle subproject. We used to have the protocol package externally but ended up folding it in in the end so perhaps you guys should just do it.

**Comment by l-jonas** [comment]
@AudriusButkevicius The monorepo approach solves the problem that things are handled separatly (issues, pull requests, ...) altough they are closely related (e.g. a new feature which requires changes in the library and the app)

**Comment by l-jonas** [comment]
@Nutomic 

```
The command "./gradlew assembleDebug" exited with 0.
```
What you mean is caused by the fact that android itself contains bouncy castle so it's a really bad idea to include it as dependency, but this was not changed (it was and is included).

```
 The first 3 errors (out of 5) were:
  /home/travis/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcmail-jdk15on/1.59/db389ade95f48592908a84e7050a691c8834723c/bcmail-jdk15on-1.59.jar: Error: Invalid package reference in library; not included in Android: javax.activation. Referenced from org.bouncycastle.mail.smime.SMIMECompressedGenerator. [InvalidPackage]
  /home/travis/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcmail-jdk15on/1.59/db389ade95f48592908a84e7050a691c8834723c/bcmail-jdk15on-1.59.jar: Error: Invalid package reference in library; not included in Android: javax.mail.internet. Referenced from org.bouncycastle.mail.smime.SMIMECompressed. [InvalidPackage]
  /home/travis/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcmail-jdk15on/1.59/db389ade95f48592908a84e7050a691c8834723c/bcmail-jdk15on-1.59.jar: Error: Invalid package reference in library; not included in Android: javax.mail. Referenced from org.bouncycastle.mail.smime.CMSProcessableBodyPart. [InvalidPackage]
```

**Comment by l-jonas** [comment]
@Nutomic 

Interestingly, the error happens only at the CI (I think it uses a newer version of the build tools) and not at my machine. I enabled ignoring these warnings (but this is only a temporarily solution).

@AudriusButkevicius 

I would suggest waiting until <https://github.com/syncthing/syncthing/issues/5224> is done before publishing the App again at Google Play (because the App feels buggy without that).

**Comment by AudriusButkevicius** [comment]
You guys could explicitly close the connection to relieve that.

**Comment by Nutomic** [comment]
@AudriusButkevicius That's not possible if the internet was disconnected, or if the app was killed by Android.

**Pull request merged**
